repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: ./scripts/lint.sh
        language: system
        types: [file, python]
        fail_fast: true
        pass_filenames: false

