repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: ./scripts/lint.sh
        language: system
        types: [file, python]
        fail_fast: true
        pass_filenames: false
  # - repo: https://github.com/psf/black
  #   rev: 21.12b0
  #   hooks:
  #     - id: black

