[tool.poetry]
name = "fpl-coach"
version = "0.1.0"
description = ""
authors = ["Rafael Chaves <rafaelvchaves@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.3"
understat = "^0.1.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
